development:
  adapter: postgresql
  encoding: unicode
  database: taskwise_development
  pool: 5
  username: John
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: taskwise_test
  pool: 5
  username: John
  password: